name = "mala"
version = "1.0.0"
gleam = ">= 1.11.0"
description = "ETS bags, an in-memory table where one key can have multiple values"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "mala" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
